name: 'FHIR-zib compliance'
description: 'Check FHIR profile compliance to the zibs'
inputs:
    max-file:
      description: 'Path to .max file'
      required: true
    structuredefinitions:
      description: 'A glob to the structuredefinition files to check'
      required: true
    zib-release:
      description: 'The zib release to check mappings for'
      required: true
    fhir-version:
      description: 'The FHIR version to use (the "fhirVersion" element in the structuredefinitions will be ignored).\nIf the version is STU3, the definitions should be present in the "definitions" folder.'
      default: 'R4'
    restrict-missing:
      description: 'Restrict the check for missing arguments to the zibs that have been mapped to the provided profiles'
      default: true
    fail-at:
      description: The level at which issues are considered fatal (error or warning).
      default: error
    zib-deviations:
      description: 'A YAML file describing, with reason, where the profile may deviate from the zib.'
runs:
  using: 'composite'
  steps:
    - name: Check for input
      run: |
      do_run=false
      for source in ${{inputs.structuredefinitions}}; do 
        if [[ -f $source ]]; then
          do_run=true
        fi
      done
      if $do_run; then
        echo "::set-output name=run::run"
      else
        echo "No StructureDefinitions to check, skipping"
        echo "::set-output name=run::"
      fi
    id: check_run
    shell: bash
  - name: Get dependencies
    run: |
      if [ ${{ steps.check_run.outputs.run }} ]; then
        npm install --prefix ${{ github.action_path }} > /dev/null 2> /dev/null
      fi
    shell: bash
  - run: echo "::set-output name=opt_zib_deviations::$(if [ ! -z ${{inputs.zib-deviations}} ]; then echo --zib-deviations=${{ inputs.zib-deviations }};fi)"
    id: set_options
    shell: bash
  - name: Run script
    run: |
      if [ ${{ steps.check_run.outputs.run }} ]; then
        'node ${{ github.action_path }}/index.js -m ${{ inputs.max-file }} -z ${{ inputs.zib-release }} -v ${{ inputs.fhir-version }} -r ${{inputs.restrict-missing }} --fail-at ${{ inputs.fail-at }} ${{ steps.set_options.opt_zib_deviations }} -f text ${{ inputs.structuredefinitions }}'
      fi
    shell: bash
